### ISSUE TITLE
按照步骤集成，依赖不成功。

### ISSUE THREAD

**Issue by wohelu666** [Chen-Xi-g/MVVMFramework#1]
按照步骤在根build gradle 集成
![image](https://user-images.githubusercontent.com/48713628/155931769-1ff2dff2-0d97-4700-9426-2f0eb5267a2e.png)

然后再子build gradle 集成
![image](https://user-images.githubusercontent.com/48713628/155931827-9a7bf30a-e3a7-41d8-b8b0-82e059086405.png)
 一直失败。
![image](https://user-images.githubusercontent.com/48713628/155931888-fd17cd4a-2619-4a35-96c6-28c1a47e13b5.png)

**Comment by Chen-Xi-g** [comment]
由于工作繁忙，还没有进一步维护，如果项目着急建议你下载代码，然后集成到项目的Module中。大概这周末时候会对库完善。

**Comment by wohelu666** [comment]
好的，已经弄好了，期待完善的版本。

**Comment by Chen-Xi-g** [comment]
@wohelu666 框架中如果发现使用问题，欢迎提出，我会进一步的完善。最近由于工作导致库被耽搁。

**Comment by wohelu666** [comment]
我看里面封装部分方法没用到，能否在新版本里面使用起来，这样在用的时候就能更清楚的某个方法的用途。

**Comment by Chen-Xi-g** [comment]
好的，后面有时间我会写一个Sample程序

**Comment by wohelu666** [comment]
好的，谢谢。

**Comment by Chen-Xi-g** [comment]
目前只能通过 WanAndroid 的开放API构建一个 Sample 程序，你有更好的推荐吗？

**Comment by wohelu666** [comment]
我所知道的也就是wanAndroid 的Api.没有其他推荐了呢。

**Comment by Chen-Xi-g** [comment]
更新了AndroidStudio Template插件， 可以尝试使用。并且可以直接使用依赖进行集成。[AlvinMVVMPlugin_4_3](https://github.com/Chen-Xi-g/AlvinMVVMPlugin_4_3)

**Comment by wohelu666** [comment]
已经看到了。

**Comment by wohelu666** [comment]
项目修改以后，依旧运行不起来，报错如下图：
![image](https://user-images.githubusercontent.com/48713628/160523689-8b878f03-29e7-422b-a290-b8e8862f3839.png)

**Comment by Chen-Xi-g** [comment]
gradle具体代码提供一下

**Comment by wohelu666** [comment]
![image](https://user-images.githubusercontent.com/48713628/160578837-c6785ece-540c-475d-a159-91052a42c10f.png)

**Comment by Chen-Xi-g** [comment]
把buildScript上一行的注释删掉试试

**Comment by Chen-Xi-g** [comment]
主要原因是你的Gradle版本太低了
![image](https://user-images.githubusercontent.com/37918545/160579243-1850ff03-f94a-466a-8e40-9abe14ff9f25.png)

**Comment by wohelu666** [comment]
也有可能吧，不知道要改哪里，可能需要升级AS才能用。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chen-Xi-g/MVVMFramework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 下午5:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chen-Xi-g/MVVMFramework] 按照步骤集成，依赖不成功。 (Issue #1)





 
把buildScript上一行的注释删掉试试

**Comment by wohelu666** [comment]
![image](https://user-images.githubusercontent.com/48713628/160579525-fb7d3cc2-5b4b-4ef1-8718-978e5e4cb919.png)

**Comment by Chen-Xi-g** [comment]
[Android Gradle 插件版本说明](https://developer.android.com/studio/releases/gradle-plugin)
