### ISSUE TITLE
okhttp的自定义的ssl能添加上吗

### ISSUE THREAD

**Issue by sanpark** [Chen-Xi-g/MVVMFramework#2]

**Comment by Chen-Xi-g** [comment]
当时没考虑到这些，下一个版本我会添加一个获取okHttpClient函数的方法。

**Comment by Chen-Xi-g** [comment]
![image](https://user-images.githubusercontent.com/37918545/164708259-4e9beb2d-9b0b-4ab5-b517-eef2e00917f4.png)
version 1.1.2已更新。稍后你可以通过这种方式初始化，获取OkHttpClient.Builder进行自定义。
