### ISSUE TITLE
使用默认的配置，添加一个mvvmfragment.报错view must have a tag

### ISSUE THREAD

**Issue by sanpark** [Chen-Xi-g/MVVMFramework#3]
使用默认的配置，添加一个mvvmfragment.报错view must have a tag
`class MineFragment : BaseMVVMFragment<MineViewModel, NewappFragMineBinding>(R.layout.newapp_frag_mine) {

    override fun initView(view: View, savedInstanceState: Bundle?) {
    }

    override fun lazyLoadData() {
    }

    override fun obtainData() {
    }

    override fun registerObserver() {

    }
}`

资源文件都是唯一的 没有重复的文件

**Comment by sanpark** [comment]
其实能不能提供viewbinding 的基类

**Comment by Chen-Xi-g** [comment]
项目是用dataBinding来集成的，既然是mvvm就需要用到dataBinding了。

**Comment by Chen-Xi-g** [comment]
在build.gradle把databinding打开。
```

android{

    ...

   buildFeatures {
        dataBinding true
    }

   ...

}

```

**Comment by Chen-Xi-g** [comment]
> 使用默认的配置，添加一个mvvmfragment.报错view must have a tag `class MineFragment : BaseMVVMFragment<MineViewModel, NewappFragMineBinding>(R.layout.newapp_frag_mine) {
> 
> ```
> override fun initView(view: View, savedInstanceState: Bundle?) {
> }
> 
> override fun lazyLoadData() {
> }
> 
> override fun obtainData() {
> }
> 
> override fun registerObserver() {
> 
> }
> ```
> 
> }`
> 
> 资源文件都是唯一的 没有重复的文件

发一下布局文件代码。

**Comment by sanpark** [comment]
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <data>

    </data>

    <androidx.core.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/colorCommonBack"
        android:overScrollMode="never">

        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/colorCommonBack">

            <ImageView
                android:id="@+id/iv_head_ring"
                android:layout_width="64dp"
                android:layout_height="64dp"
                android:layout_centerVertical="true"
                android:layout_marginStart="16dp"
                android:layout_marginTop="18dp"
                android:background="@drawable/shape_white_c_ffffff"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

            <ImageView
                android:id="@+id/iv_head"
                android:layout_width="60dp"
                android:layout_height="60dp"
                android:layout_marginStart="18dp"
                android:layout_marginTop="20dp"
                android:src="@drawable/ic_default_photo"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

            <TextView
                android:id="@+id/tv_name"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="12dp"
                android:gravity="end"
                android:textColor="#262D49"
                android:textSize="18sp"
                android:textStyle="bold"
                app:layout_constraintBottom_toTopOf="@+id/tv_alarm"
                app:layout_constraintStart_toEndOf="@+id/iv_head"
                app:layout_constraintTop_toTopOf="@+id/iv_head"
                tools:text="名字" />

            <TextView
                android:id="@+id/tv_alarm"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="14dp"
                android:textColor="#666666"
                android:textSize="15sp"
                app:layout_constraintBottom_toBottomOf="@+id/iv_head"
                app:layout_constraintStart_toEndOf="@+id/iv_head"
                app:layout_constraintTop_toBottomOf="@id/tv_name"
                tools:text="101010001" />

            <TextView
                android:id="@+id/tv_edit"
                android:layout_width="75dp"
                android:layout_height="25dp"
                android:layout_marginEnd="16dp"
                android:background="@drawable/shape_green_r14_30c971"
                android:gravity="center"
                android:text="编辑资料"
                android:textColor="@color/color_white"
                android:textSize="12sp"
                app:layout_constraintBottom_toBottomOf="@+id/iv_head"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintTop_toTopOf="@+id/iv_head" />

            <androidx.constraintlayout.widget.ConstraintLayout
                android:id="@+id/cl_mid"
                android:layout_width="match_parent"
                android:layout_height="72dp"
                android:layout_marginStart="16dp"
                android:layout_marginTop="20dp"
                android:layout_marginEnd="16dp"
                android:background="@drawable/ic_me_background"
                android:elevation="1dp"
                android:gravity="center"
                android:orientation="horizontal"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/iv_head">

                <View
                    android:id="@+id/line_mid"
                    android:layout_width="1dp"
                    android:layout_height="28dp"
                    android:background="#1AEEEEEE"
                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent" />

                <TextView
                    android:id="@+id/tv_organization"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:drawableStart="@drawable/ic_me_org"
                    android:drawablePadding="10dp"
                    android:gravity="center"
                    android:text="所属单位"
                    android:textColor="#FFFFFF"
                    android:textSize="13sp"
                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintEnd_toStartOf="@+id/line_mid"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent" />


                <TextView
                    android:id="@+id/tv_code"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:drawableStart="@drawable/ic_me_code"
                    android:drawablePadding="10dp"
                    android:gravity="center"
                    android:text="二维码"
                    android:textColor="#ffffff"
                    android:textSize="13sp"
                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toEndOf="@+id/line_mid"
                    app:layout_constraintTop_toTopOf="parent" />

            </androidx.constraintlayout.widget.ConstraintLayout>

            <androidx.appcompat.widget.LinearLayoutCompat
                android:id="@+id/ll_voice"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginTop="16dp"
                android:background="@drawable/shape_white_r16_ffffff"
                android:orientation="vertical"
                app:layout_constraintEnd_toEndOf="@+id/cl_mid"
                app:layout_constraintStart_toStartOf="@+id/cl_mid"
                app:layout_constraintTop_toBottomOf="@+id/cl_mid">

                <androidx.constraintlayout.widget.ConstraintLayout
                    android:layout_width="match_parent"
                    android:layout_height="46dp"
                    android:layout_gravity="center_vertical"
                    android:paddingStart="16dp"
                    android:paddingEnd="16dp">

                    <TextView
                        android:id="@+id/tv_ringing"
                        android:layout_width="0dp"
                        android:layout_height="0dp"
                        android:drawableStart="@drawable/ic_me_voice"
                        android:drawableEnd="@drawable/ic_arrow_right_green"
                        android:drawablePadding="14dp"
                        android:gravity="center_vertical"
                        android:text="声音与触感"
                        android:textColor="#000000"
                        android:textSize="14sp"
                        app:layout_constraintBottom_toBottomOf="parent"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="parent" />

                </androidx.constraintlayout.widget.ConstraintLayout>
            </androidx.appcompat.widget.LinearLayoutCompat>

            <androidx.appcompat.widget.LinearLayoutCompat
                android:id="@+id/ll_password"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginTop="16dp"
                android:background="@drawable/shape_white_r16_ffffff"
                android:orientation="vertical"
                app:layout_constraintEnd_toEndOf="@+id/cl_mid"
                app:layout_constraintStart_toStartOf="@+id/cl_mid"
                app:layout_constraintTop_toBottomOf="@+id/ll_voice">

                <androidx.constraintlayout.widget.ConstraintLayout
                    android:layout_width="match_parent"
                    android:layout_height="102dp"
                    android:layout_gravity="center_vertical"
                    android:paddingStart="16dp"
                    android:paddingTop="5dp"
                    android:paddingEnd="16dp"
                    android:paddingBottom="5dp">

                    <TextView
                        android:id="@+id/tv_password_modify"
                        android:layout_width="0dp"
                        android:layout_height="46dp"
                        android:drawableStart="@drawable/ic_me_password"
                        android:drawableEnd="@drawable/ic_arrow_right_green"
                        android:drawablePadding="14dp"
                        android:gravity="center_vertical"
                        android:text="修改密码"
                        android:textColor="#000000"
                        android:textSize="14sp"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="parent" />

                    <TextView
                        android:id="@+id/tv_fingerprint"
                        android:layout_width="0dp"
                        android:layout_height="46dp"
                        android:drawableStart="@drawable/ic_me_fingerprint"
                        android:drawableEnd="@drawable/ic_arrow_right_green"
                        android:drawablePadding="14dp"
                        android:gravity="center_vertical"
                        android:text="指纹登录"
                        android:textColor="#000000"
                        android:textSize="14sp"
                        app:layout_constraintBottom_toBottomOf="parent"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toBottomOf="@id/tv_password_modify" />

                </androidx.constraintlayout.widget.ConstraintLayout>
            </androidx.appcompat.widget.LinearLayoutCompat>

            <androidx.appcompat.widget.LinearLayoutCompat
                android:id="@+id/ll_location"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginTop="16dp"
                android:background="@drawable/shape_white_r16_ffffff"
                android:orientation="vertical"
                app:layout_constraintEnd_toEndOf="@+id/cl_mid"
                app:layout_constraintStart_toStartOf="@+id/cl_mid"
                app:layout_constraintTop_toBottomOf="@+id/ll_password">

                <androidx.constraintlayout.widget.ConstraintLayout
                    android:layout_width="match_parent"
                    android:layout_height="46dp"
                    android:layout_gravity="center_vertical"
                    android:paddingStart="16dp"
                    android:paddingEnd="16dp">

                    <TextView
                        android:id="@+id/textView16"
                        android:layout_width="0dp"
                        android:layout_height="0dp"
                        android:drawableStart="@drawable/ic_me_location"
                        android:drawablePadding="14dp"
                        android:gravity="center_vertical"
                        android:text="共享位置"
                        android:textColor="#000000"
                        android:textSize="14sp"
                        app:layout_constraintBottom_toBottomOf="parent"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="parent" />

                    <Switch
                        android:id="@+id/switch_location"
                        android:layout_width="52dp"
                        android:layout_height="32dp"
                        android:switchMinWidth="0dp"
                        android:textOff=""
                        android:textOn=""
                        android:thumb="@drawable/switch_thumb"
                        android:track="@drawable/switch_track"
                        app:layout_constraintBottom_toBottomOf="parent"
                        app:layout_constraintEnd_toEndOf="@+id/textView16"
                        app:layout_constraintTop_toTopOf="parent" />
                </androidx.constraintlayout.widget.ConstraintLayout>
            </androidx.appcompat.widget.LinearLayoutCompat>

            <androidx.appcompat.widget.LinearLayoutCompat
                android:id="@+id/ll_setting"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginTop="16dp"
                android:background="@drawable/shape_white_r16_ffffff"
                android:orientation="vertical"
                app:layout_constraintEnd_toEndOf="@+id/cl_mid"
                app:layout_constraintStart_toStartOf="@+id/cl_mid"
                app:layout_constraintTop_toBottomOf="@+id/ll_location">

                <androidx.constraintlayout.widget.ConstraintLayout
                    android:layout_width="match_parent"
                    android:layout_height="148dp"
                    android:layout_gravity="center_vertical"
                    android:paddingStart="16dp"
                    android:paddingTop="5dp"
                    android:paddingEnd="16dp"
                    android:paddingBottom="5dp">

                    <TextView
                        android:id="@+id/tv_version_num_info"
                        android:layout_width="0dp"
                        android:layout_height="46dp"
                        android:drawableStart="@drawable/ic_me_version"
                        android:drawableEnd="@drawable/ic_arrow_right_green"
                        android:drawablePadding="14dp"
                        android:gravity="center_vertical"
                        android:text="当前版本"
                        android:textColor="#000000"
                        android:textSize="14sp"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="parent" />

                    <TextView
                        android:id="@+id/tv_version_num"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_marginEnd="16dp"
                        android:paddingTop="10dp"
                        android:paddingBottom="10dp"
                        android:textColor="#333333"
                        android:textSize="12sp"
                        app:layout_constraintBottom_toBottomOf="@+id/tv_version_num_info"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintTop_toTopOf="@+id/tv_version_num_info"
                        tools:text="版本号" />

                    <TextView
                        android:id="@+id/tv_suggestion"
                        android:layout_width="0dp"
                        android:layout_height="46dp"
                        android:drawableStart="@drawable/ic_me_suggestion"
                        android:drawableEnd="@drawable/ic_arrow_right_green"
                        android:drawablePadding="14dp"
                        android:gravity="center_vertical"
                        android:text="意见反馈"
                        android:textColor="#000000"
                        android:textSize="14sp"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toBottomOf="@id/tv_version_num_info" />

                    <TextView
                        android:id="@+id/tv_system_setting"
                        android:layout_width="0dp"
                        android:layout_height="46dp"
                        android:drawableStart="@drawable/ic_me_system"
                        android:drawableEnd="@drawable/ic_arrow_right_green"
                        android:drawablePadding="14dp"
                        android:gravity="center_vertical"
                        android:text="系统设置"
                        android:textColor="#000000"
                        android:textSize="14sp"
                        app:layout_constraintBottom_toBottomOf="parent"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toBottomOf="@id/tv_suggestion" />

                </androidx.constraintlayout.widget.ConstraintLayout>
            </androidx.appcompat.widget.LinearLayoutCompat>

            <TextView
                android:id="@+id/tv_logout"
                android:layout_width="0dp"
                android:layout_height="40dp"
                android:layout_marginTop="32dp"
                android:layout_marginBottom="32dp"
                android:background="@drawable/shape_black_r20_262d49"
                android:gravity="center"
                android:text="退出登录"
                android:textColor="#ffffff"
                android:textSize="14sp"
                android:textStyle="bold"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="@+id/cl_mid"
                app:layout_constraintStart_toStartOf="@+id/cl_mid"
                app:layout_constraintTop_toBottomOf="@+id/ll_setting" />

        </androidx.constraintlayout.widget.ConstraintLayout>

    </androidx.core.widget.NestedScrollView>
</layout>

**Comment by sanpark** [comment]
`
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <data>

    </data>

    <androidx.core.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/colorCommonBack"
        android:overScrollMode="never">

     

    </androidx.core.widget.NestedScrollView>
</layout>
`

**Comment by sanpark** [comment]
> > 使用默认的配置，添加一个mvvmfragment.报错view must have a tag `class MineFragment : BaseMVVMFragment<MineViewModel, NewappFragMineBinding>(R.layout.newapp_frag_mine) {
> > ```
> > override fun initView(view: View, savedInstanceState: Bundle?) {
> > }
> > 
> > override fun lazyLoadData() {
> > }
> > 
> > override fun obtainData() {
> > }
> > 
> > override fun registerObserver() {
> > 
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }`
> > 资源文件都是唯一的 没有重复的文件
> 
> 发一下布局文件代码。

我用你的插件生成的 fragment 一样也有这个问题 activity没有这个问题
我是同时使用  
  buildFeatures {
        viewBinding true
        dataBinding true
    }
然后在viewpager里面加载这个fragment 会报这个错误

**Comment by Chen-Xi-g** [comment]
尝试把出错的布局文件删除后重新创建

**Comment by sanpark** [comment]
qq能通过下吗？详细的内容我截图给您

**Comment by Chen-Xi-g** [comment]
布局文件名称冲突导致。
